language: node_js
node_js:
  - v12
after_script: cat ./coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: Skerwe/generator-game-generic
